[supabase]
url = "https://hqjmnyixijzdrcjbwite.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxam1ueWl4aWp6ZHJjamJ3aXRlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NjQzMDc1OSwiZXhwIjoyMDYyMDA2NzU5fQ.EemCOEeCGOJipXHNpYACqqjhDVJE7LxLtmfLRuXrANE"
